# Generated by Django 5.2.16 on 2026-08-08 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_rename_user_complaint_sender_complaint_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress / On-Going'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('revoked', 'Revoked / Cancelled')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Finance.complaint')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
